name: Create Datadog Resources

on:
  push:
    paths:
      - '**/dashboard.json'
  workflow_dispatch:
  
jobs:
  create-resources:
    runs-on: ubuntu-latest
    env:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      DATADOG_APP_KEY: ${{ secrets.DATADOG_APP_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install datadog

      - name: Run create_dashboard script
        run: |
          pwd
          python dashboard.py
