name: Create Datadog Resources

on:
  push:
    paths:
      - '**/dashboard.json'
  workflow_dispatch:

jobs:
  create-resources:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install datadog

      - name: Process client directories
        run: |
          for client_dir in $(find . -maxdepth 1 -type d -name 'client*'); do
            if [ -f "$client_dir/dashboard.json" ]; then
              echo "Processing $client_dir/dashboard.json"
              python - <<EOF
from datadog import initialize, api
import json
import os

# Initialize Datadog
options = {
    'api_key': os.getenv('DATADOG_API_KEY'),
    'app_key': os.getenv('DATADOG_APP_KEY'),
    'api_host': 'https://api.us5.datadoghq.com'
}

initialize(**options)

# Create Dashboard
with open('${client_dir}/dashboard.json', 'r') as file:
    dashboard_data = json.load(file)
response = api.Dashboard.create(**dashboard_data)
print("Dashboard created for ${client_dir}:", response)
EOF
            fi
          done
        env:
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
          DATADOG_APP_KEY: ${{ secrets.DATADOG_APP_KEY }}
